// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iynXhXnMynQqSMKMmL-E62KoBKfWgU4',
    appId: '1:414029629569:web:4c5e2a6867a4dd3132a580',
    messagingSenderId: '414029629569',
    projectId: 'repositoryviewer-82621',
    authDomain: 'repositoryviewer-82621.firebaseapp.com',
    storageBucket: 'repositoryviewer-82621.firebasestorage.app',
    measurementId: 'G-V66SQQW2P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsomC0qiqHfUfKbPpCctHRYZtX-F6QiJA',
    appId: '1:414029629569:android:6ee670e938c7834e32a580',
    messagingSenderId: '414029629569',
    projectId: 'repositoryviewer-82621',
    storageBucket: 'repositoryviewer-82621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJa39FK5ipq2-AZej90XVZj0RX2OJwS80',
    appId: '1:414029629569:ios:c85d5984cf0aea2632a580',
    messagingSenderId: '414029629569',
    projectId: 'repositoryviewer-82621',
    storageBucket: 'repositoryviewer-82621.firebasestorage.app',
    iosBundleId: 'com.example.repositoryviewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJa39FK5ipq2-AZej90XVZj0RX2OJwS80',
    appId: '1:414029629569:ios:c85d5984cf0aea2632a580',
    messagingSenderId: '414029629569',
    projectId: 'repositoryviewer-82621',
    storageBucket: 'repositoryviewer-82621.firebasestorage.app',
    iosBundleId: 'com.example.repositoryviewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9iynXhXnMynQqSMKMmL-E62KoBKfWgU4',
    appId: '1:414029629569:web:f290cb9dc1f5c1e832a580',
    messagingSenderId: '414029629569',
    projectId: 'repositoryviewer-82621',
    authDomain: 'repositoryviewer-82621.firebaseapp.com',
    storageBucket: 'repositoryviewer-82621.firebasestorage.app',
    measurementId: 'G-FX0S1L8V48',
  );
}
